name: Security SBOM Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-security-scan:
    uses: testAhmal-devsecops-lab/devsecops-orchestrator/.github/workflows/reusable-dtrack.yml@main
    secrets:
      DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
